### PR TITLE
Fixes AR-1618 npm blurb text

### PR DESCRIPTION
**Pull request by shaloo**
Description update npm blurb for DKG open source library. First draft for review.

### CODE REVIEW

**Comment by shaloo** [comment]
@makylfang: Does this npm blurb description field update require any modifications or can it be merged?  I'd like to close AR-1618 once this is taken care of.

**Review by makylfang — CHANGES_REQUESTED** [review]
I think a more accurate description can be "Key management library for secure and simple public/private key retrieval from Arcana distributed key generation system"

**Comment by shaloo** [comment]
Alright, so keystore is only enabling retrieval of public/private key from Arcana DKG. From user's (dAPp dev and their end user) PoV this library is a meant to help them manage their keys. THat is all.  These are not 'own keys' but keys generated using Arcana DKG.  They needn't bother to remember to store them but they can use keystore library to securely retrieve public/private (dKG generated) Arcana keys.  Do they use socialauth to authenticate with keystore and then retrieve the keys - just trying to understand use model better.

**Comment by shaloo** [comment]
THere are just two APIs, should we call this library or APIs for secure and simple public/private key retrieval from Arcana distributed key generation system?

**Comment by makylfang** [comment]
> Alright, so keystore is only enabling retrieval of public/private key from Arcana DKG. From user's (dAPp dev and their end user) PoV this library is a meant to help them manage their keys. THat is all. These are not 'own keys' but keys generated using Arcana DKG. They needn't bother to remember to store them but they can use keystore library to securely retrieve public/private (dKG generated) Arcana keys - is that correct?

Yes this is correct.

>  Input = Social Auth (Google, GitHub, Reddit etc in examples src) to authenticate and then redirect to keystore and then retrieve the keys - just trying to understand use model better.

Input is social auth token and the id that the JWT provides, and then keystore sdk can be used to fetch the keys.
This library is not really user facing, its used internally by auth SDK. You use this SDK if you have usage of social tokens in addition to what auth SDK provides(fetching pvt/pub key). For example if an app wants to authenticate with github, get pvt/public key, and use github token to also fetch user repositories.

**Review by makylfang — APPROVED** [review]

**Pull request merged**
